name: Cron Job With Issue

on:
  schedule:
    - cron: "20 * * * *"
  issues:
    types: [opened,deleted,edited,transferred,pinned,unpinned,closed]

jobs:
  run-log:
    runs-on: ubuntu-latest
    steps:
      - name: create log
        run: |
          echo "${{ github.event_name }}"