name: First Action

on: [push]

jobs:
  run-mac-terminal-command:
    runs-on: macos-lastest
    steps:
      - name: check node version
        run: |
          node -v
          npm -v
  run-after-mac-terminal-command:
    runs-on: macos-lastest
    needs: ["run-mac-terminal-command"]
    steps:
      - name: log
        run: |
          echo "Mac terminal is done"
