name: First Action

on: [push]

jobs:
  run-mac-terminal-command:
    runs-on: [macos-11]
    steps:
      - name: check node version
        run: |
          node -v
          npm -v
  run-after-mac-terminal-command:
    runs-on: macos-11
    needs: ["run-mac-terminal-command"]
    steps:
      - name: log
        run: |
          echo "Mac terminal is done"
  run-another-repository-action:
    runs-on: [macos-11]
    steps:
      - name: hello
        run: |
          pwd
          ls -a
      - name: hello
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Kuro'
