name: Run action by label

on:
  issues:
    types: [labeled]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'todo'
    steps:
      - name: log
        uses: peter-evans/create-or-update-comment@v1
        with:
          body: |
            Todo list:
            [] check this
          reactions: eyes
